### PR TITLE
 #22 make it channel - resilient

### PR DESCRIPTION
**Pull request by JoeZ99**
this is to do with #22 
frankly, I don't know if it's worth it. As it was, the app reconnected automatically when conn was lost. Now the app reconnects automatically when channel is lost, assuming `AMQP` revamps the channel.

Anyway, of course it's a mayor version change.

Also, now the `amqp` `channels` option must be always configured when using this app. Update README with that ...

I do like that it somehow separates things, and let `AMQP` to worry about maintaining `channel name` and conn, instead of this library handling it itself

### CODE REVIEW

**Review by agutierrezrodriguez — APPROVED** [review]

**Review by jbonet-df — APPROVED** [review]

**Review by sonic182 — APPROVED** [review]
We may need to specify heartbeat of 1min instead of 10s default??

Also, we may need ChannelWatch or similar to watch the channel process? well, that's for Consumer case, not sure if here we need it

**Comment by JoeZ99** [comment]
> We may need to specify heartbeat of 1min instead of 10s default??

@sonic182 , If it worked so far, why change it? @agutierrezrodriguez what do you think??

**Comment by agutierrezrodriguez** [comment]
> > We may need to specify heartbeat of 1min instead of 10s default??
> 
> @sonic182 , If it worked so far, why change it? @agutierrezrodriguez what do you think??

maybe @sonic182 knows something that we do not!

**Comment by sonic182** [comment]
I guess that for events_manager it's ok without a channel watcher, as Supervisor will restart the terminated genserver

**Comment by JoeZ99** [comment]
Exactly the same is achieved. Do you see any difference??

**Pull request merged**
